name: ch_data_asset
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.3
  flutter:
    sdk: flutter
  get_storage: ^2.0.3
  supabase_flutter: ^0.3.1
  avatar_glow: ^2.0.2
  barcode_widget: ^2.0.2
  carousel_slider: ^4.1.1
  intl: ^0.17.0
  image_picker: ^0.8.5+3
  path_provider: ^2.0.10
  flutter_barcode_scanner: ^2.0.0
  google_fonts: ^3.0.1
  flutter_switch: ^0.3.2
  currency_text_input_formatter: ^2.1.7
  dropdown_button2: ^1.7.2
  pattern_formatter: ^2.0.0
  supabase: ^0.3.6


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: helvetica_bold
      fonts:
        - asset: assets/fonts/helveticaneue/Helvetica_Neu_Bold.ttf
    - family: HelveticaNeue_BlackCond
      fonts:
        - asset: assets/fonts/helveticaneue/HelveticaNeue_BlackCond.ttf
    - family: HelveticaNeue_Light
      fonts:
        - asset: assets/fonts/helveticaneue/HelveticaNeue_Light.ttf
    - family: helvetica_medium
      fonts:
        - asset: assets/fonts/helveticaneue/HelveticaNeue_Medium.ttf
    - family: HelveticaNeue_Thin
      fonts:
        - asset: assets/fonts/helveticaneue/HelveticaNeue_Thin.ttf
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/helveticaneue/HelveticaNeue.ttf
    - family: HelveticaNeueBd
      fonts:
        - asset: assets/fonts/helveticaneue/HelveticaNeueBd.ttf
    - family: HelveticaNeueHv
      fonts:
        - asset: assets/fonts/helveticaneue/HelveticaNeueHv.ttf
    - family: HelveticaNeueIt
      fonts:
        - asset: assets/fonts/helveticaneue/HelveticaNeueIt.ttf
    - family: HelveticaNeueLt
      fonts:
        - asset: assets/fonts/helveticaneue/HelveticaNeueLt.ttf
    - family: HelveticaNeueMed
      fonts:
        - asset: assets/fonts/helveticaneue/HelveticaNeueMed.ttf
    - family: FreeSansReg
      fonts:
        - asset: assets/fonts/helveticaneue/FreeSans.ttf
    - family: FreeSansBold
      fonts:
        - asset: assets/fonts/helveticaneue/FreeSansBold.ttf

  assets:
    - assets/images/
    - assets/icons/
